server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Permitir acceso a los symlinks (catalog.csv y covers)
    location /covers/ {
        alias /data/covers/;
    }
}
