server {
    listen 80;
    server_name _;   # Responde a cualquier nombre de dominio

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /data/ {
        alias /data/;
    }
}
